#!/usr/bin/env node
"use strict";
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const ROOT=path.resolve(__dirname,"..");
const DIST=path.join(ROOT,"dist");
const OUT=path.join(DIST,"parseraccs");
const SOURCE=path.join(ROOT,"parseraccs.js");
const LOADER=path.join(ROOT,"src","loader.js");
const BASE="https://fbads.fun/parseraccs";
const CHUNK_SIZE=350000;
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const hash=s=>crypto.createHash("sha256").update(s).digest("hex");
const write=(file,data)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data)};
const pretty=p=>`${BASE}/${p}`.replace(/\.html$/,"");
const build=process.env.BUILD_VERSION||require(path.join(ROOT,"package.json")).version;
if(!/^[0-9A-Za-z._-]+$/.test(build)) throw new Error("Invalid BUILD_VERSION");
const source=fs.readFileSync(SOURCE,"utf8");
const loader=fs.readFileSync(LOADER,"utf8");
const base64=Buffer.from(source,"utf8").toString("base64");
const chunks=[];for(let i=0;i<base64.length;i+=CHUNK_SIZE)chunks.push(base64.slice(i,i+CHUNK_SIZE));
const buildDir=path.join(OUT,build), latestDir=path.join(OUT,"latest");
fs.rmSync(buildDir,{recursive:true,force:true});fs.rmSync(latestDir,{recursive:true,force:true});
const ogHtml=(chunk,i)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta property="og:type" content="website"><meta property="og:title" content="ParserAccs ${esc(build)} chunk ${i+1}/${chunks.length}"><meta property="og:description" content="${esc(chunk)}"><title>ParserAccs ${esc(build)} chunk ${i+1}/${chunks.length}</title></head><body><pre>ParserAccs ${esc(build)} chunk ${i+1}/${chunks.length}</pre></body></html>`;
write(path.join(buildDir,"payload.js"),source);write(path.join(latestDir,"payload.js"),source);
chunks.forEach((chunk,i)=>{const f=`chunk-${String(i+1).padStart(3,"0")}.html`;const html=ogHtml(chunk,i);write(path.join(buildDir,"og",f),html);write(path.join(latestDir,"og",f),html)});
const manifest={app:"ParserAccs",build,version:build,generatedAt:new Date().toISOString(),payload:{encoding:"base64",sha256:hash(source),byteLength:Buffer.byteLength(source)},chunks:chunks.map((chunk,i)=>({index:i+1,file:`og/chunk-${String(i+1).padStart(3,"0")}.html`,url:pretty(`${build}/og/chunk-${String(i+1).padStart(3,"0")}.html`),latestUrl:pretty(`latest/og/chunk-${String(i+1).padStart(3,"0")}.html`),base64Length:chunk.length,base64Sha256:hash(chunk)}))};
const manifest64=Buffer.from(JSON.stringify(manifest),"utf8").toString("base64");
const manifestHtml=`<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta property="og:type" content="website"><meta property="og:title" content="ParserAccs ${esc(build)} manifest"><meta property="og:description" content="${esc(manifest64)}"><title>ParserAccs ${esc(build)} manifest</title></head><body><pre>ParserAccs ${esc(build)} manifest</pre></body></html>`;
write(path.join(buildDir,"manifest.html"),manifestHtml);write(path.join(latestDir,"manifest.html"),manifestHtml);
const loaderFor=lang=>loader.replaceAll("__PARSERACCS_LANG__",lang);
const hrefFor=lang=>`javascript:${encodeURIComponent(loaderFor(lang))}`;
const packageInfo={...manifest,latestManifestUrl:pretty("latest/manifest.html"),manualScrapeUrls:[pretty("latest/manifest.html"),...manifest.chunks.map(x=>x.latestUrl)]};
write(path.join(buildDir,"package-info.json"),JSON.stringify(packageInfo,null,2)+"\n");write(path.join(latestDir,"package-info.json"),JSON.stringify(packageInfo,null,2)+"\n");
write(path.join(latestDir,"tool-meta.json"),JSON.stringify({app:"ParserAccs",title:"ParserAccs",build,version:build,landingUrl:"https://fbads.fun/",sourceUrl:"https://github.com/Kw3nty/ParserAccs",bookmarkletHref:hrefFor("ru"),bookmarkletHrefEn:hrefFor("en"),latestManifestUrl:packageInfo.latestManifestUrl,generatedAt:manifest.generatedAt},null,2)+"\n");
let landing=fs.readFileSync(path.join(ROOT,"site","index.html"),"utf8");
const marker="/* ===== ГИБРИДНАЯ СБОРКА букмарклета из модулей src/ ===== */";
const init="/* ===== инициализация ===== */";
const a=landing.indexOf(marker),b=landing.indexOf(init,a);if(a<0||b<0)throw new Error("Landing build markers missing");
const replacement=`/* ===== Стабильный self-updating loader ===== */\nwindow.__pa_code_ru=${JSON.stringify(hrefFor("ru"))};\nwindow.__pa_code_en=${JSON.stringify(hrefFor("en"))};\nwindow.__pa_cur_code=siteLang==='en'?window.__pa_code_en:window.__pa_code_ru;\nfunction buildBookmarklet(){var link=document.getElementById('bm-link'),copy=document.getElementById('bm-copy'),warn=document.getElementById('warn'),drag=document.querySelector('.drag-hint'),status=document.getElementById('build-status'),version=document.getElementById('build-version'),rebuild=document.getElementById('bm-rebuild');window.__pa_cur_code=siteLang==='en'?window.__pa_code_en:window.__pa_code_ru;link.href=window.__pa_cur_code;link.classList.remove('loading');link.textContent='📌 ParserAccs';link.title=siteLang==='en'?'Drag me to your bookmarks bar':'Перетащи меня на панель закладок';link.style.filter='';if(status){status.className='ready';status.textContent=siteLang==='en'?'✓ Loader ready':'✓ Loader готов';}if(version)version.textContent='build · ${build} · loader';if(drag)drag.style.display='flex';if(warn)warn.style.display='none';if(copy)copy.disabled=false;if(rebuild)rebuild.disabled=false;applyLanguage(siteLang,false);}\n\n`;
landing=landing.slice(0,a)+replacement+landing.slice(b);
write(path.join(DIST,"index.html"),landing);
{const ad=path.join(ROOT,"site","assets"),dd=path.join(DIST,"assets");fs.mkdirSync(dd,{recursive:true});for(const f of fs.readdirSync(ad))fs.copyFileSync(path.join(ad,f),path.join(dd,f))}
fs.copyFileSync(path.join(ROOT,"LICENSE"),path.join(DIST,"LICENSE"));
{const sd=path.join(ROOT,"docs","screenshots");if(fs.existsSync(sd)){const dd=path.join(DIST,"docs","screenshots");fs.mkdirSync(dd,{recursive:true});for(const f of fs.readdirSync(sd))fs.copyFileSync(path.join(sd,f),path.join(dd,f))}}
write(path.join(DIST,"_headers"),"/\n  Cache-Control: no-store\n\n/parseraccs/*\n  Access-Control-Allow-Origin: *\n  Cache-Control: no-store\n");
write(path.join(DIST,"_redirects"),"/ /index.html 200\n");
console.log(`ParserAccs ${build} packaged: ${chunks.length} OG chunk(s).`);console.log("Manual Facebook scrape URLs:");packageInfo.manualScrapeUrls.forEach(x=>console.log(`- ${x}`));
